/*
 * Message.java
 *
 * Created on October 12, 2007, 12:37 PM
 */

package com.krcl.cc;

/**
 *
 * @author  Prajakta
 */
public class Message extends javax.swing.JDialog {
    
    /** Creates new form Message */
    public Message (java.awt.Frame parent, boolean modal) {
        super (parent, modal);
        initComponents ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        lblMessage = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Information");
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMessage);
        lblMessage.setBounds(0, 0, 400, 120);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        getContentPane().add(btnOK);
        btnOK.setBounds(70, 130, 90, 25);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        getContentPane().add(btnCancel);
        btnCancel.setBounds(170, 130, 90, 25);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-350)/2, (screenSize.height-200)/2, 350, 200);
    }//GEN-END:initComponents

    private void btnCancelActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose ();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        new Message (new javax.swing.JFrame (), true).show ();
    }
    
    /**
     * Getter for property message.
     * @return Value of property message.
     */
    public java.lang.String getMessage () {
        return message;
    }
    
    /**
     * Setter for property message.
     * @param message New value of property message.
     */
    public void setMessage (java.lang.String message) {
        this.message = message;
        lblMessage.setText (message);
    }
    
    public void isCancelRequired (boolean flag) {
        btnCancel.setVisible (flag);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables

    private String message;    
    
}
