/*
 * PrintDTC.java
 *
 * Created on May 5, 2006, 1:33 AM
 */

package com.krcl.cc;

/**
 *
 * @author  Prajakta
 */
public class PrintDTC extends javax.swing.JFrame {
    
    /** Creates new form PrintDTC */
    public PrintDTC () {
        initComponents ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        paneReport = new javax.swing.JDesktopPane();
        tblItem = new javax.swing.JTable();
        tblCash = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        tblItem.setBorder(new javax.swing.border.CompoundBorder(null, new javax.swing.border.CompoundBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)))));
        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, new Integer(0), new Integer(0)},
                {null, null, null}
            },
            new String [] {
                "Item", "Summer", "Monsoon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblItem.setColumnSelectionAllowed(true);
        tblItem.setTableHeader(null);
        tblItem.setBounds(10, 26, 300, 40);
        paneReport.add(tblItem, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tblCash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Receipts", "Vouchers", "Title 4", "Title 5"
            }
        ));
        tblCash.setBounds(10, 90, -1, -1);
        paneReport.add(tblCash, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(paneReport, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm (java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        new PrintDTC ().show ();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane paneReport;
    private javax.swing.JTable tblCash;
    private javax.swing.JTable tblItem;
    // End of variables declaration//GEN-END:variables
    
}
